---
# Create a user. The application will run as this user.
- name: Add the app user
  ansible.builtin.user:
    name: "{{ app_user_name }}"
    home: "{{ app_user_home }}"
    shell: /usr/bin/false
    system: yes

# Cloning the source code from the Google Cloud Repository
- name: Clone app repo 
  ansible.builtin.git:
    repo: "{{ app_repo_url }}"
    dest: "{{ proj_path }}"
    force: yes

# Update pip, pip from apt is out of date  
- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    executable: pip3
    state: latest

# Install virtualenv
- name: Install virtualenv module
  ansible.builtin.pip:
    name: virtualenv
    state: latest

# Install app dependencies
- name: Install requirements
  ansible.builtin.pip:
    requirements: "{{ app_requirements }}"
    virtualenv: "{{ venv_path }}"
    virtualenv_command: virtualenv
    virtualenv_python: python3.7

- name: Recursively change ownership
  ansible.builtin.file:
    path: "{{ proj_path }}"
    state: directory
    recurse: yes
    owner: "{{ app_user_name }}"
    group: "{{ app_user_name }}"

- name: Create config.py using Jinja2
  ansible.builtin.template:
    src: "{{ config_py_tmplt }}"
    dest: "{{ app_path }}/config.py"

- name: Configure supervisor using Jinja2
  ansible.builtin.template:
    src: "{{ supervisor_tmplt }}"
    dest: "/etc/supervisor/conf.d/{{ supervisor_conf_name }}"

- name: Restart supervisor
  ansible.builtin.service:
    name: supervisor.service
    state: restarted

# DB tables init
- name: Initialize the database tables
  ansible.builtin.command: "{{ venv_path }}/bin/python {{ app_path }}/bookshelf/model_cloudsql.py"
