---
- name: Get server info about data, uptime and updates
  hosts: KBKDATASRV01
  gather_facts: false
  tasks:
    - name: Get uptime info
      shell: /usr/bin/uptime
      register: uptimeinfo

    - name: Get date info
      shell: date
      register: dateinfo

    - name: Upgradable package nummber
      shell: apt list --upgradable | wc -l
      register: upgradableinfo
      
    - name: info
      debug: 
        msg:
        - " {{ upgradableinfo.stdout }} updates can be applied immediately"
        - "it is {{ dateinfo.stdout }} "
        - "and system working without reboot for {{ uptime.stdout }} "