---
- name: Get server uptime
  hosts: KBKDATASRV01
  gather_facts: false
  tasks:
    - name: Get uptime info
      shell: uptime
      register: uptimeinfo

    - debug: msg="{{ uptimeinfo.stdout }}"

    - name: Get date info
      shell: date
      register: datainfo

    - debug: msg="{{ datainfo.stdout }}"

    - name: Upgradable package nummber
      shell: apt list --upgradable | wc -l
      register: upgradableinfo

    - name: Print return information from the previous task
      debug:
        var: upgradableinfo
        verbosity: 2

    - debug: msg="{{ upgradableinfo.stdout }}"
