---
- name: Get server uptime
  hosts: KBKDATASRV01
  tasks:
    - name: Get uptime first
      shell: uptime
      register: hello
    - debug: msg="{{ hello.stdout }}"
    - debug: msg="{{ hello.stderr }}"
    - name: Get date second
      shell: date
      register: hello
    - debug: msg="{{ hello.stdout }}"
    - debug: msg="{{ hello.stderr }}"

    - name: upgradable package nummber
      shell: apt list --upgradable | wc -l
      register: upgradable
    - debug: msg="{{ upgradable.stdout }}"
    - debug: msg="{{ upgradable.stderr }}"