---
- name: Get server uptime
  hosts: KBKDATASRV01
  tasks:
    - name: Get uptime info
      shell: uptime
      register: uptimeinfo
    
    - name: Get date info
      shell: date
      register: datainfo

    - name: upgradable package nummber
      shell: apt list --upgradable | wc -l
      register: upgradable

    - debug: msg="{{ uptimeinfo.stdout }}"
    - debug: msg="{{ datainfo.stdout }}"
    - debug: msg="{{ upgradable.stdout }}"

