---
- name: Get server info about data, uptime and updates
  hosts: KBKDATASRV01
  gather_facts: false
  tasks:
    - name: Get uptime info
      shell: /usr/bin/uptime
      register: uptimeinfo
    - debug: msg="{{ uptimeinfo.stdout }}"

    - name: Get date info
      shell: date
      register: dateinfo
    - debug: msg="{{ dateinfo.stdout }}"

    - name: Upgradable package nummber
      shell: apt list --upgradable | wc -l
      register: upgradableinfo

    - name: Print return information from the previous task
      debug:
        var: upgradableinfo
        verbosity: 2

    - name: total
      debug: 
        msg:
        - "{{ upgradableinfo.stdout }} updates can be applied immediately"
        - "it is {{ ansible_date_time }}"