---
- name: Get server info about data, uptime and updates
  hosts: KBKDATASRV01
  gather_facts: false
  tasks:
    - name: Get uptime info
      shell: /usr/bin/uptime -p
      register: uptimeinfo 

    - name: Get date info
      shell: date
      register: dateinfo

    - name: Upgradable package nummber
      shell: apt list --upgradable | wc -l
      register: upgradableinfo
      
    - name: some system info before update
      debug: 
        msg:
        - "There are {{ upgradableinfo.stdout }} updates can be applied immediately"
        - "System is {{ uptimeinfo.stdout }} without reboot"
        - "It is {{ dateinfo.stdout }} system data"
        